baseURL = "https://eletiva2ano.netlify.app/"
locale = "pt-BR"
theme = "dream"
defaultContentLanguage = "pt"
title = "Eletiva"

[services]
  [services.googleAnalytics]
    ID = "G-L8XNN582QM"
  [services.disqus]
    shortname = "eletiva2ano"

[params]
  author = "Vinícius"
  description = "Um site desenvolvido por alunos do ensino médio com objetivo de transmitir conhecimento" # descrição que irá aparecer nos buscadores
  avatar = "/img/banco-de-fotos/Foto_Site.jpeg"
  headerTitle = "Eletiva"
  motto = '"O importante é não parar de questionar." - Albert Einstein' # descrição que fica no site
  showSummaryCoverInPost = true

  lightTheme = "emerald"
  darkTheme = "forest"

  favicon = "/img/banco-de-fotos/Foto_Site.jpeg"

  # RSS
  rss = true

  siteStartYear = 2021

  [params.advanced]
    customCSS = ["css/custom.css"]
